pipeline{
  agent any
  tools {
    terraform "terraform"
  }
  stages{
    stage("Git Checkout"){
      steps{
            git branch: 'master', url: 'https://github.com/uddasp/learn-terraform-provision-eks-cluster.git'
           }
        }
    stage('Terraform Init') {
      steps {
        sh label: '', script: 'terraform init'
      }
    }
    stage('Terraform apply') {
      steps {
        sh label: '', script: 'terraform destroy --auto-approve'
      }
    }
  }
}
